//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingYourPackage.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentState
    {
        public System.Guid Key { get; set; }
        public System.Guid ShipmentKey { get; set; }
        public int ShipmentStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
